name: dart_crypt
description: CLI application that provides encryption and decryption capabilities for your sensitive data.
# TODO Implement automatic version control system
# While bumping the version validate integrity with lib/config/version.dart file.
version: 0.5.0
repository: https://github.com/rozpo/dart_crypt

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.4.2
  cli_completion: ^0.3.0
  encrypt: ^5.0.1
  errno: ^1.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dcrypt:
